# Generated by Django 4.2.1 on 2023-05-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_pizzatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='pizza_types',
            field=models.ManyToManyField(to='pizza.pizzatype'),
        ),
    ]
